# Generated by Django 3.1.5 on 2021-01-05 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DockerFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/dockerfiles/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/models/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('docker_image_id', models.CharField(blank=True, default='', max_length=100)),
                ('dockerfile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dockerfile',
                                                 to='dwmodel.dockerfile')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modelfile',
                                            to='dwmodel.modelfile')),
            ],
        ),
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100)),
                ('description', models.TextField()),
                ('docker_container_id', models.CharField(blank=True, default='', max_length=100)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dwmodel.image')),
            ],
        ),
    ]
