# Generated by Django 3.1.5 on 2021-01-06 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dwmodel', '0002_auto_20210106_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dockerfile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='modelfile',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
