# Generated by Django 3.1.5 on 2021-01-06 05:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('dwmodel', '0003_auto_20210106_1038'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='model',
            new_name='modelfile',
        ),
    ]
