# Generated by Django 3.1.5 on 2021-01-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dwmodel', '0004_auto_20210106_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
