# Generated by Django 3.1.5 on 2021-01-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dwmodel', '0005_auto_20210106_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='container',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
