# Generated by Django 3.1.5 on 2021-01-07 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('dwmodel', '0006_auto_20210107_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='port_in',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='container',
            name='port_out',
            field=models.IntegerField(default=80),
        ),
    ]
